// Build the Job-AI Chrome extension into extension/dist.
// The agents reuse the desktop app's modules (bot/modules/*.js) so there is ONE copy of the
// automation logic. Two build-time adjustments make that code run in an extension:
//   1. Desktop-only modules (fs, config, llm, stealth, captcha...) are swapped for browser shims.
//   2. Chrome extensions can't run code handed to them at runtime, but the shared code passes
//      small functions to run in the page (page.evaluate(fn), element.evaluate(fn)). The build
//      collects every such function into a pre-bundled list (src/generated/ops.js) and rewrites
//      each call to name its function by id. The app's own source files are never modified.
import * as esbuild from 'esbuild';
import { cpSync, mkdirSync, rmSync, copyFileSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import * as acorn from 'acorn';
import * as walk from 'acorn-walk';
import MagicString from 'magic-string';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const out = resolve(here, 'dist');
const watch = process.argv.includes('--watch');
// --test: keep the test hook and source maps. Release builds (default) ship neither.
const test = process.argv.includes('--test') || watch;

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
cpSync(resolve(here, 'public'), out, { recursive: true });
// PDF reader (CV text) runs its worker from a bundled file; Word reader is a browser build.
copyFileSync(resolve(root, 'node_modules/pdfjs-dist/build/pdf.worker.min.mjs'), resolve(out, 'pdf.worker.min.mjs'));
// Same look as the desktop app: its own stylesheet and fonts, copied at build time so the two
// never drift apart. dashboard.css only adds the few extension-only pieces.
copyFileSync(resolve(root, 'src/renderer/styles.css'), resolve(out, 'app.css'));
cpSync(resolve(root, 'src/renderer/fonts'), resolve(out, 'fonts'), { recursive: true });
copyFileSync(resolve(root, 'src/renderer/brand-logo.png'), resolve(out, 'brand-logo.png'));

// ── 2. Collect page functions and rewrite their calls ───────────────────────────
// Methods whose FUNCTION argument runs in the page: name -> index of that argument.
const PAGE_FN = { evaluate: 0, evaluateHandle: 0, waitForFunction: 0, $eval: 1, $$eval: 1 };
const MODULES = resolve(root, 'bot/modules');
const registry = new Map(); // id -> function source

function transform(code, file) {
  let ast;
  try { ast = acorn.parse(code, { ecmaVersion: 'latest', sourceType: 'script', allowReturnOutsideFunction: true, allowHashBang: true }); }
  catch (e) { console.warn('  [build] could not parse', basename(file), e.message); return null; }
  const ms = new MagicString(code);
  let n = 0;
  walk.full(ast, (node) => {
    if (node.type !== 'CallExpression' || node.callee.type !== 'MemberExpression' || node.callee.computed) return;
    const name = node.callee.property.name;
    if (!(name in PAGE_FN)) return;
    const fn = node.arguments[PAGE_FN[name]];
    if (!fn || !/^(ArrowFunctionExpression|FunctionExpression)$/.test(fn.type)) return;
    const src = code.slice(fn.start, fn.end);
    const id = 'f' + createHash('sha1').update(src).digest('hex').slice(0, 12);
    registry.set(id, src);
    // obj.evaluate(fn, a)  ->  obj.__call("evaluate", "id", fn, a)
    ms.overwrite(node.callee.property.start, node.callee.property.end, '__call');
    ms.appendLeft(node.arguments[0].start, `${JSON.stringify(name)}, ${JSON.stringify(id)}, `);
    n++;
  });
  return n ? ms.toString() : code;
}

// Pre-scan every shared module so the page-side registry is complete before bundling.
for (const f of readdirSync(MODULES).filter((x) => x.endsWith('.js'))) transform(readFileSync(resolve(MODULES, f), 'utf8'), f);
mkdirSync(resolve(here, 'src/generated'), { recursive: true });
writeFileSync(resolve(here, 'src/generated/ops.js'),
  '// GENERATED by extension/build.mjs from bot/modules/*.js. Do not edit.\n// Every function the shared agent code runs inside a web page, bundled by id.\nmodule.exports = {\n' +
  [...registry].map(([id, src]) => `  ${JSON.stringify(id)}: ${src},`).join('\n') + '\n};\n');
console.log(`  [build] ${registry.size} page functions bundled`);

// ── 1. Desktop-only modules -> browser shims ────────────────────────────────────
const S = (f) => resolve(here, 'src/shims', f);
const shims = {
  name: 'jobai-shims',
  setup(b) {
    b.onResolve({ filter: /^\.\.?\/config$/ }, (a) => (/[\\/]bot([\\/]|$)/.test(a.resolveDir) ? { path: S('config.js') } : null));
    b.onResolve({ filter: /services\/llm$/ }, () => ({ path: S('llm.js') }));
    b.onResolve({ filter: /^\.\/llm$/ }, (x) => (/services[\\/]tracImporter/.test(x.importer) ? { path: S('llm.js') } : null));
    b.onResolve({ filter: /^\.\/cvAnalyzer$/ }, () => ({ path: S('cvAnalyzer.js') }));
    b.onResolve({ filter: /^(node:)?fs$/ }, () => ({ path: S('fs.js') }));
    b.onResolve({ filter: /^(node:)?path$/ }, () => ({ path: S('path.js') }));
    b.onResolve({ filter: /^\.\/(stealth|captcha_solver|queue_manager)$/ }, () => ({ path: S('noop.js') }));
    b.onResolve({ filter: /^\.\/cv_validate$/ }, () => ({ path: S('cv_validate.js') }));
    b.onResolve({ filter: /^pdfkit$/ }, () => ({ path: resolve(root, 'node_modules/pdfkit/js/pdfkit.standalone.js') }));
    // Shared agent modules: rewrite page functions to call them by id.
    b.onLoad({ filter: /[\\/]bot[\\/]modules[\\/][^\\/]+\.js$/ }, (a) => {
      const code = readFileSync(a.path, 'utf8');
      return { contents: transform(code, a.path) ?? code, loader: 'js' };
    });
  },
};

const common = {
  bundle: true,
  format: 'esm',
  target: 'chrome116',
  platform: 'browser',
  sourcemap: test ? 'linked' : false,
  minify: !test || process.argv.includes('--min'),
  logLevel: 'warning',
  plugins: [shims],
  // A few settings the desktop code reads from process.env.
  define: { 'process.env.JOBBOT_LICENSE_KEY': 'globalThis.__jobaiLicense', 'process.env.JOBBOT_ALLOW_LOCAL_LLM': 'undefined', 'process.env.JOBBOT_AIFILL_MS': 'undefined', 'process.env.JOBBOT_AIFILL_DEBUG': 'undefined', 'process.env.JOBBOT_TRAC_RESUME': 'undefined', 'process.env.JOBAI_TEST': test ? '"1"' : '"0"' },
};

const builds = [
  { ...common, entryPoints: { background: resolve(here, 'src/background.js'), dashboard: resolve(here, 'src/dashboard.js') }, outdir: out },
  // Injected into job pages: selector engine + named/bundled page functions. Plain script.
  { ...common, format: 'iife', entryPoints: { helper: resolve(here, 'src/driver/helper.js') }, outdir: out },
];

if (watch) {
  for (const b of builds) (await esbuild.context(b)).watch();
  console.log('Watching…');
} else {
  for (const b of builds) await esbuild.build(b);
  console.log('Built to', out);
}
